name: ci-casper-rust-contract

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        components: rustfmt, clippy
    # Needed for gcc install
    - run: sudo apt update && sudo apt install -y build-essential wabt
    - run: make prepare
    - run: make check-lint
    - run: make test